pipeline {
    agent any

    parameters {
        booleanParam(defaultValue: false, description: "Deploy the App", name: "DEPLOY")
    }

    stages {
        stage("Build") {
            steps {
                sh "mvn -B -DskipTests clean package"
            }
        }
        stage("Test") {
            steps {
                sh "mvn test"
            }
            post {
                always {
                    junit "target/surefire-reports/*.xml"
                }
            }
        }
        stage("Deliver") {
            when {
                expression { params.DEPLOY }
            }
            steps {
                sh "docker run mpapp:latest"
            }
        }
        stage("Package") {
            steps {
                withCredentials([string(credentialsId: "DockerHub", variable: "TOKEN")]) {
                    sh "docker login -u 'j13jha' -p '$TOKEN' docker.io"
                    sh "docker build -t myapp:latest --tag j13jha/acit4850_samplejava:myapp ."
                    sh "docker push j13jha/acit4850_samplejava:myapp"
                }
            }
        }
    }
}
